package CIan.GMtest;

public class SM2test {
    public static void main(String[] args) throws Exception{
        String str = "everything";
        String certInfo = "-----BEGIN CERTIFICATE-----\r\n"
                + "MIIBrTCCAVICCQCxYpYSzXCIRzAKBggqgRzPVQGDdTBeMQswCQYDVQQGEwJDTjEL\r\n"
                + "MAkGA1UECAwCSEYxCzAJBgNVBAcMAkhGMQ8wDQYDVQQKDAZIU0JBTksxDTALBgNV\r\n"
                + "BAsMBFRFU1QxFTATBgNVBAMMDFRFU1QgTUVSQ0hOVDAeFw0yMTExMDgwNjU4Mzla\r\n"
                + "Fw0zMTExMDYwNjU4MzlaMF4xCzAJBgNVBAYTAkNOMQswCQYDVQQIDAJIRjELMAkG\r\n"
                + "A1UEBwwCSEYxDzANBgNVBAoMBkhTQkFOSzENMAsGA1UECwwEVEVTVDEVMBMGA1UE\r\n"
                + "AwwMVEVTVCBNRVJDSE5UMFkwEwYHKoZIzj0CAQYIKoEcz1UBgi0DQgAEEK5LRFTv\r\n"
                + "uODEaW1GWPLsT1PwyOs4KyKUA5OT92BD5mmqCNejc+x4WYaT2sTArkiH4At8C4xl\r\n"
                + "Eq15hSuxBt95hDAKBggqgRzPVQGDdQNJADBGAiEA2tMG8OCrzQ7485duxy+ZtOBK\r\n"
                + "qoBoIGNNUOT4DFo236YCIQDOkzg47NsjiLzXVpzfF4hS41QPFgY5yWD+OM2KNy+U\r\n" + "jw==\r\n"
                + "-----END CERTIFICATE-----";
        String privatePem = "MIGHAgEAMBMGByqGSM49AgEGCCqBHM9VAYItBG0wawIBAQQg1eGvibIkTl8gsrE76MhYb7rn6wv34uul59OSKh8Q1i2hRANCAAQQrktEVO+44MRpbUZY8uxPU/DI6zgrIpQDk5P3YEPmaaoI16Nz7HhZhpPaxMCuSIfgC3wLjGUSrXmFK7EG33mE";
        System.out.println(CIan.GM.SM2Api.SM2SignPemPKCS7(certInfo, privatePem, str));
        String sign = "MIICxQYKKoEcz1UGAQQCAqCCArUwggKxAgEDMQ4wDAYIKoEcz1UBgxEFADAMBgoqgRzPVQYBBAIBoIIBsTCCAa0wggFSAgkAsWKWEs1wiEcwCgYIKoEcz1UBg3UwXjELMAkGA1UEBhMCQ04xCzAJBgNVBAgMAkhGMQswCQYDVQQHDAJIRjEPMA0GA1UECgwGSFNCQU5LMQ0wCwYDVQQLDARURVNUMRUwEwYDVQQDDAxURVNUIE1FUkNITlQwHhcNMjExMTA4MDY1ODM5WhcNMzExMTA2MDY1ODM5WjBeMQswCQYDVQQGEwJDTjELMAkGA1UECAwCSEYxCzAJBgNVBAcMAkhGMQ8wDQYDVQQKDAZIU0JBTksxDTALBgNVBAsMBFRFU1QxFTATBgNVBAMMDFRFU1QgTUVSQ0hOVDBZMBMGByqGSM49AgEGCCqBHM9VAYItA0IABBCuS0RU77jgxGltRljy7E9T8MjrOCsilAOTk/dgQ+ZpqgjXo3PseFmGk9rEwK5Ih+ALfAuMZRKteYUrsQbfeYQwCgYIKoEcz1UBg3UDSQAwRgIhANrTBvDgq80O+POXbscvmbTgSqqAaCBjTVDk+AxaNt+mAiEAzpM4OOzbI4i811ac3xeIUuNUDxYGOclg/jjNijcvlI8xgdgwgdUCAQEwazBeMQswCQYDVQQGEwJDTjELMAkGA1UECAwCSEYxCzAJBgNVBAcMAkhGMQ8wDQYDVQQKDAZIU0JBTksxDTALBgNVBAsMBFRFU1QxFTATBgNVBAMMDFRFU1QgTUVSQ0hOVAIJALFilhLNcIhHMAwGCCqBHM9VAYMRBQAwDAYIKoEcz1UBgi0FAARHMEUCIEzGstcqjboXxAihKiwohVDDaaQDdd0DCiU1WV98oetuAiEAx2JK2a5d0manc391zy27jpIRSx/2rSnx0ikuIGYhNQs=";
        System.out.println(CIan.GM.SM2Api.SM2VerifyCertPKCS7(str, sign));
    }
}

